/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerAppointmentsRouteImport } from './routes/customer/appointments'
import { Route as CustomerBookRouteImport } from './routes/customer/book'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardOperationsRouteImport } from './routes/dashboard/operations'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardWorkersRouteImport } from './routes/dashboard/workers'
import { Route as WorkerIndexRouteImport } from './routes/worker/index'
import { Route as WorkerAppointmentsRouteImport } from './routes/worker/appointments'
import { Route as WorkerProfileRouteImport } from './routes/worker/profile'
import { Route as WorkerScheduleRouteImport } from './routes/worker/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAppointmentsRoute = CustomerAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookRoute = CustomerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOperationsRoute = DashboardOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersRoute = DashboardWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashboardRoute,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerAppointmentsRoute = WorkerAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerScheduleRoute = WorkerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => WorkerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/worker': typeof WorkerRouteWithChildren
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/worker/appointments': typeof WorkerAppointmentsRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/schedule': typeof WorkerScheduleRoute
  '/customer/': typeof CustomerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/worker/appointments': typeof WorkerAppointmentsRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/schedule': typeof WorkerScheduleRoute
  '/customer': typeof CustomerIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/worker': typeof WorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/worker': typeof WorkerRouteWithChildren
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/worker/appointments': typeof WorkerAppointmentsRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/schedule': typeof WorkerScheduleRoute
  '/customer/': typeof CustomerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/customer'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/solutions'
    | '/worker'
    | '/customer/appointments'
    | '/customer/book'
    | '/customer/profile'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/operations'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/workers'
    | '/worker/appointments'
    | '/worker/profile'
    | '/worker/schedule'
    | '/customer/'
    | '/dashboard/'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/solutions'
    | '/customer/appointments'
    | '/customer/book'
    | '/customer/profile'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/operations'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/workers'
    | '/worker/appointments'
    | '/worker/profile'
    | '/worker/schedule'
    | '/customer'
    | '/dashboard'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/customer'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/solutions'
    | '/worker'
    | '/customer/appointments'
    | '/customer/book'
    | '/customer/profile'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/operations'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/workers'
    | '/worker/appointments'
    | '/worker/profile'
    | '/worker/schedule'
    | '/customer/'
    | '/dashboard/'
    | '/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  WorkerRoute: typeof WorkerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/appointments': {
      id: '/customer/appointments'
      path: '/appointments'
      fullPath: '/customer/appointments'
      preLoaderRoute: typeof CustomerAppointmentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/book': {
      id: '/customer/book'
      path: '/book'
      fullPath: '/customer/book'
      preLoaderRoute: typeof CustomerBookRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operations': {
      id: '/dashboard/operations'
      path: '/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof DashboardOperationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers': {
      id: '/dashboard/workers'
      path: '/workers'
      fullPath: '/dashboard/workers'
      preLoaderRoute: typeof DashboardWorkersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/appointments': {
      id: '/worker/appointments'
      path: '/appointments'
      fullPath: '/worker/appointments'
      preLoaderRoute: typeof WorkerAppointmentsRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/schedule': {
      id: '/worker/schedule'
      path: '/schedule'
      fullPath: '/worker/schedule'
      preLoaderRoute: typeof WorkerScheduleRouteImport
      parentRoute: typeof WorkerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerAppointmentsRoute: typeof CustomerAppointmentsRoute
  CustomerBookRoute: typeof CustomerBookRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAppointmentsRoute: CustomerAppointmentsRoute,
  CustomerBookRoute: CustomerBookRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardOperationsRoute: typeof DashboardOperationsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWorkersRoute: typeof DashboardWorkersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardOperationsRoute: DashboardOperationsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWorkersRoute: DashboardWorkersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface WorkerRouteChildren {
  WorkerAppointmentsRoute: typeof WorkerAppointmentsRoute
  WorkerProfileRoute: typeof WorkerProfileRoute
  WorkerScheduleRoute: typeof WorkerScheduleRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerAppointmentsRoute: WorkerAppointmentsRoute,
  WorkerProfileRoute: WorkerProfileRoute,
  WorkerScheduleRoute: WorkerScheduleRoute,
  WorkerIndexRoute: WorkerIndexRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomerRoute: CustomerRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  WorkerRoute: WorkerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
